In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('50_Startups.csv')

In [3]:
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
data.tail()

R&D Spend  Administration  Marketing Spend       State    Profit
45    1000.23       124153.04          1903.93    New York  64926.08
46    1315.46       115816.21        297114.46     Florida  49490.75
47       0.00       135426.92             0.00  California  42559.73
48     542.05        51743.15             0.00    New York  35673.41
49       0.00       116983.80         45173.06  California  14681.40

In [5]:
data.keys()

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [6]:
data.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [7]:
data.shape

(50, 5)

In [8]:
data.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [9]:
data.describe()

R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
R&D Spend          50 non-null float64
Administration     50 non-null float64
Marketing Spend    50 non-null float64
State              50 non-null object
Profit             50 non-null float64
dtypes: float64(4), object(1)
memory usage: 2.0+ KB


In [11]:
x = data.iloc[:, :-1].values
y = data.iloc[:, 4].values

In [12]:
x.shape

(50, 4)

In [13]:
y.shape

(50,)

In [14]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
df=data.apply(label.fit_transform)
df.head()

R&D Spend  Administration  Marketing Spend  State  Profit
0         48              34               47      2      49
1         47              41               46      0      48
2         46              11               45      1      47
3         45              22               44      2      46
4         44               6               43      1      45

In [15]:
#from numpy
x=np.array(df[['R&D Spend', 'Administration', 'Marketing Spend', 'State']])
y=np.array(df[['Profit']])

In [16]:
x

array([[48, 34, 47,  2],
       [47, 41, 46,  0],
       [46, 11, 45,  1],
       [45, 22, 44,  2],
       [44,  6, 43,  1],
       [42, 10, 42,  2],
       [43, 39, 10,  0],
       [41, 38, 40,  1],
       [39, 40, 39,  2],
       [40, 14, 38,  0],
       [36, 15, 24,  1],
       [35,  7, 25,  0],
       [33, 28, 26,  1],
       [32, 33, 27,  0],
       [38, 47, 28,  1],
       [37, 24, 29,  2],
       [28, 23, 30,  0],
       [34, 37, 31,  2],
       [31, 17, 32,  1],
       [30, 44,  0,  2],
       [26, 16, 34,  0],
       [29, 45, 35,  2],
       [24, 25, 36,  1],
       [22, 13, 37,  1],
       [27,  9, 13,  2],
       [19, 35, 12,  0],
       [25, 36, 11,  1],
       [23, 30, 41,  2],
       [21, 49,  9,  1],
       [20, 43,  8,  2],
       [17, 18,  7,  1],
       [16, 42,  6,  2],
       [18, 31,  5,  0],
       [15, 12, 23,  1],
       [14, 48, 22,  0],
       [13,  5, 21,  2],
       [ 9, 27, 20,  1],
       [12,  0, 19,  0],
       [ 5,  2, 18,  2],
       [11,  3, 17,  0],


In [17]:
y

array([[49],
       [48],
       [47],
       [46],
       [45],
       [44],
       [43],
       [42],
       [41],
       [40],
       [39],
       [38],
       [37],
       [36],
       [35],
       [34],
       [33],
       [32],
       [31],
       [30],
       [29],
       [28],
       [27],
       [26],
       [25],
       [24],
       [23],
       [22],
       [21],
       [20],
       [19],
       [18],
       [17],
       [16],
       [15],
       [14],
       [13],
       [12],
       [11],
       [10],
       [ 9],
       [ 8],
       [ 7],
       [ 6],
       [ 5],
       [ 4],
       [ 3],
       [ 2],
       [ 1],
       [ 0]], dtype=int64)

In [18]:
#from pandas
x = df.iloc[:, :-1].values
y = df.iloc[:, 4].values
x

array([[48, 34, 47,  2],
       [47, 41, 46,  0],
       [46, 11, 45,  1],
       [45, 22, 44,  2],
       [44,  6, 43,  1],
       [42, 10, 42,  2],
       [43, 39, 10,  0],
       [41, 38, 40,  1],
       [39, 40, 39,  2],
       [40, 14, 38,  0],
       [36, 15, 24,  1],
       [35,  7, 25,  0],
       [33, 28, 26,  1],
       [32, 33, 27,  0],
       [38, 47, 28,  1],
       [37, 24, 29,  2],
       [28, 23, 30,  0],
       [34, 37, 31,  2],
       [31, 17, 32,  1],
       [30, 44,  0,  2],
       [26, 16, 34,  0],
       [29, 45, 35,  2],
       [24, 25, 36,  1],
       [22, 13, 37,  1],
       [27,  9, 13,  2],
       [19, 35, 12,  0],
       [25, 36, 11,  1],
       [23, 30, 41,  2],
       [21, 49,  9,  1],
       [20, 43,  8,  2],
       [17, 18,  7,  1],
       [16, 42,  6,  2],
       [18, 31,  5,  0],
       [15, 12, 23,  1],
       [14, 48, 22,  0],
       [13,  5, 21,  2],
       [ 9, 27, 20,  1],
       [12,  0, 19,  0],
       [ 5,  2, 18,  2],
       [11,  3, 17,  0],


In [19]:
y

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0],
      dtype=int64)

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=6)

In [21]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [22]:
x_train.shape

(40, 4)

In [23]:
y_train.shape

(40,)

In [24]:
x_test.shape

(10, 4)

In [25]:
y_test.shape

(10,)

In [26]:
y_pred = regressor.predict(x_test)
y_pred

array([ 1.45986878, 11.64652523,  5.10999628, 23.19734662, 42.2915248 ,
       48.62146989, 44.48492834, 15.86620655, 39.1227181 , 16.0276591 ])

In [28]:
test_score=regressor.score(x_test,y_test)
test_score

0.9698867652737803

In [29]:
train_score=regressor.score(x_train,y_train)
train_score

0.9826347230387095

In [30]:
df1 = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})  
df1 

Actual  Predicted
0       0   1.459869
1       9  11.646525
2      11   5.109996
3      26  23.197347
4      42  42.291525
5      49  48.621470
6      43  44.484928
7      15  15.866207
8      35  39.122718
9      18  16.027659

In [31]:
from sklearn import metrics  
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred))) 

Mean Absolute Error: 2.191529990964206
Mean Squared Error: 7.575285327727848
Root Mean Squared Error: 2.7523236233640564


In [32]:
b=regressor.intercept_
print(b)
#both are same
print(regressor.intercept_)

1.293400876032937
1.293400876032937


In [33]:
m=regressor.coef_
print(m)
#both are same
print(regressor.coef_)

[ 0.99595646  0.00461545  0.0185397  -0.75306621]
[ 0.99595646  0.00461545  0.0185397  -0.75306621]
